import asyncio
from actions import Actions
from events import Events
from state import State

import logging
log = logging.getLogger('main')

# class Handler:
#     _handlers = 0

#     async def _handle(self, event, action, cooldown=0, *args, **kwargs):
#         self.event = event
#         self.action = action
#         self.cooldown = cooldown
#         self._handlers += 1

#         await self.handle(self, *args, **kwargs)
    
#     async def handle(self, *args, **kwargs):
#         pass


# class Indentify(Handler):
#     def handle(self, event):
#         if event['type'] == "on_startup":
#             Actions.identify(event['payload'])

async def indentify(payload):
    await Actions.identify(payload)
    name = await Events.identified()
    # State.set_identified(name)

# def set_identified(name):

async def ping():
    await Actions.ping()

async def get_rooms_and_join():
    await Actions.get_room_lists()
    all_channels = await asyncio.gather(
        Events.public_channel_list,
        Events.private_rooms_list
    )
    State.set_channels(all_channels) # Is the map from title to id in place here?
    await Actions.join_channels() 
    # need to await task that waits for server
    # rooms = await [Event.public_channel_list, Event.private_rooms_list] 
    # I'd love to be able to await Event.X
    # And sometimes need to wait for multiple events
    # DataStore['rooms'] = rooms

# async def join_rooms(channels):
#     await Actions.join_channels(channels)

# # async def set_server_data(characters):
# #     State.store_characters(characters)
# set_server_data = State.set_server_data

# # async def add_channels(channels):
# #     State.add_channels(channels)
# add_channels = State.set_channels

# # async def set_channel_data(channel, data):
# #     State.
# set_channel_data = State.set_channel_data

# from State import *

async def log_error(number, message):
    log.error(f"F-list server sent an error: #{number}: {message}")

_default_handlers = {
    "on_startup": [indentify], 
    # join_rooms depends on get_rooms, should join_rooms depend on event generated by action get_rooms?
    "on_connected": [get_rooms_and_join],
    "on_ping": [ping],
    "on_identified": [State.set_identified],
    "on_public_channel_list": [State.add_channels],
    "on_private_rooms_list": [State.add_channels],
    "on_channel_message": [],
    "on_chatops_list": [],
    "on_promoted_chatop": [],
    "on_admin_broadcast": [],
    "on_channel_description": [State.set_channel_data],
    "on_invited_to_channel": [State.join_channel],
    "on_character_banned": [State.remove_character],
    "on_character_kicked": [State.remove_character],
    "on_promoted_channel_op": [State.set_channel_data],
    "on_channel_ops_list": [State.set_channel_data],
    "on_removed_channel_op": [State.set_channel_data],
    "on_character_set_as_owner": [State.set_channel_data],
    "on_character_timed_out": [],
    "on_demoted_chatop": [],
    "on_error_occurred": [log_error],
    "on_character_kink_search_response": [],
    "on_logged_out": [State.remove_character],
    "on_hello_response": [State.set_server_variables],
    "on_channel_data": [State.set_channel_data],
    "on_character_joined": [State.add_character],
    "on_kinks_data": [],
    "on_character_left_channel": [],
    "on_character_list": [State.add_characters],
    "on_character_connected": [State.add_characters],
    "on_ignore_list": [],
    "on_friends_list": [],
    "on_profile_data": [],
    "on_private_message": [],
    "on_channel_message": [],
    "on_roleplay_ad_message": [],
    "on_dice_result": [],
    "on_channel_mode_changed": [State.set_channel_mode],
    "on_received_note": [],
    "on_admin_issue": [],
    "on_character_status": [],
    "on_system_message": [],
    "on_character_typing": [],
    "on_uptime": [State.set_uptime],
    "on_server_variables": [State.set_server_variables],
}


# look up decorators again
# def on_message(handler, *args, **kwargs):
#     def decorator(handler, *args, **kwargs):

#         _default_handlers["on_channel_message"].append(handler)
    
#     return decorator

# def on_message(handler):
#     def inner(*args, **kwargs):
#         Handler.handlers["message"].append(handler)

#     return inner

###
# Handlers should be able to recognize when arbitrary events occur and respond in kind
#
# things to respond to
# - messages in chat
# - someone joining the room
# - clock/timed event
# - playing a game in chat
# - random event
# - room invitations
# - friend requests
#

#     def __init__(self, event, action, cooldown=0):
#         self.event = event
#         self.action = action
#         self.cooldown = cooldown
#         self.last_triggered = 0

#     def trigger(self):
#         if (self.event.triggered and 
#             time.time() > self.last_triggered + self.cooldown):

#             self.action.do()
#             self.last_triggered = time.time()